config/routes.rb
Hippo::Application.routes.draw do
  resources :instances  do
    member do
      get :instance_status
    end
  end


  resources :cloud_providers do
    resources :instances do
      member do
        get :resize_server
        get :stop
        get :start
        get :reboot
      end
    end
  end



  get "homes/index"
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions


  resources :html do
    collection do
      get :sign_up
      get :dashboard_none
      get :dashboard
    end
  end
  root :to => 'homes#index'
end

app/models/instance.rb
# == Schema Information
#
# Table name: instances
#
#  id                :integer          not null, primary key
#  title             :string(255)
#  instance_id       :string(255)
#  state             :string(255)
#  flavor_id         :string(255)
#  name              :string(255)
#  private_ip        :string(255)
#  public_ip         :string(255)
#  cloud_provider_id :string(255)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  image_id          :string(255)
#  progress          :string(255)
#

class Instance < ActiveRecord::Base
  attr_accessible :title, :body, :instance_id, :state, :flavor_id, :name,:private_ip, :public_ip, :image_id, :progress
  #validates_presence_of :name

  belongs_to :cloud_provider

  #
  # fetch instances
  #
  def self.get_instances connections,id
    instance_list=connections.servers
    return instance_list
  end

  #
  # stopping / starting
  #



  def stop_instance(instance)
    if instance
      puts "Stopping instance: " + instance_to_stop.inspect
      @ec2.stop_instances({:instance_id => instance})
    else
      puts "No instances to stop"
    end
  end

  def start_instances(instance)
    if instance
      puts "Starting instances: " + instance.inspect
      @compute.servers.get(instance).start
    else
      puts "No instances to start"
    end
  end  

  def create_instance(cloud_connection)
    logger.info("INside the thread ##############################")
    logger.info("##############{cloud_connection.inspect}#################")
    thread = Thread.new do
      if self.cloud_provider.type.include?("Aws")
        InstanceOperations.aws_create(cloud_connection,self)
      else
        InstanceOperations.rackspace_create(cloud_connection,self)
      end
    end
    thread.run
  end

  def resize_instance(cloud_connection)
    if self.cloud_provider.type.include?("Aws")
      InstanceOperations.resize_aws__instance(cloud_connection,self)
    else
      InstanceOperations.resize_rackspace_instance(cloud_connection,self)
    end
  end

  def stop_aws_instance(cloud_connection)
    InstanceOperations.stop_aws(self,cloud_connection)
    self.update_attributes(:state => "stopped")
  end

  def start_aws_instance(cloud_connection)
    InstanceOperations.start_aws(self,cloud_connection)
    self.update_attributes(:state => "running")
  end

  private

end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  # GET /instances
  # GET /instances.json
  before_filter :find_provider, :unless => proc{ request.xhr?   }
  def index
    @instances = @provider.instances.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @instances }
    end
  end

  # GET /instances/1
  # GET /instances/1.json
  def show
    @instance = Instance.find(params[:id])
    @flavor = Flavor.find_by_flavor_id(@instance.flavor_id)
    @image = Image.find_by_image_id(@instance.image_id)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @instance }
    end
  end

  # GET /instances/new
  # GET /instances/new.json
  def new
    @flavours = @provider.get_flavors
    puts "getting the flavors #{@flavours.inspect}"
    @images = @provider.get_images
    puts "getting the flavors #{@images.inspect}"
    @instance = @provider.instances.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @instance }
    end
  end

  # GET /instances/1/edit
  def resize_server
    @flavours = @provider.get_flavors
    puts "getting the flavors #{@flavours.inspect}"
    @instance = @provider.instances.find(params[:id])
  end

  # POST /instances
  # POST /instances.json
  def create
    @instance = @provider.instances.new(params[:instance])
    @instance.state = "Building"
    respond_to do |format|
      if @instance.save
        @instance.create_instance(@provider.connect!)
        format.html { redirect_to cloud_provider_instance_path(@provider,@instance), notice: 'Instance was successfully created.' }
        format.json { render json: @instance, status: :created, location: @instance }
      else
        format.html { render action: "new" }
        format.json { render json: @instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /instances/1
  # PUT /instances/1.json
  def update
    if request.xhr?
      @instance = Instance.find(params[:id])
    else
      @instance = @provider.instances.find(params[:id])
    end
    respond_to do |format|
      if @instance.update_attributes(params[:instance])
        @instance.resize_instance(@provider.connect!)
        format.html { redirect_to @instance, notice: 'Instance was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instances/1
  # DELETE /instances/1.json
  def destroy
    @instance = @provider.instances.find(params[:id])
    InstanceOperations.terminate_instances(@provider.connect!, @instance)
    @instance.destroy
    redirect_to cloud_provider_path(@provider)   
  end

  def instance_status
  @instance = Instance.find(params[:id])
  respond_to do | format|
      format.json { render :json => {:state => @instance.state, :progress => @instance.progress,
                                      :publicip => @instance.public_ip, :privateip => @instance.private_ip}}
    end
  end

  def start
    @instance = Instance.find params[:id]
    @instance.start_aws_instance(@provider.connect!)
    redirect_to :back
  end

  def stop
    @instance = Instance.find params[:id]
    @instance.stop_aws_instance(@provider.connect!)
    redirect_to :back
  end

  def reboot
    @instance = Instance.find params[:id]
    InstanceOperations.reboot_instances(@provider.connect!, @instance)
    redirect_to :back
  end

  private

  def find_provider
    @provider = current_user.cloud_providers.find_by_id(params[:cloud_provider_id])
    redirect_to root_path, :alert => "Sorry you are restricted to use this instance !!!" and return unless @provider.present?
  end
end

app/helpers/instances_helper.rb
module InstancesHelper
end

app/views/instances/_form.html.erb
<%= form_for [@provider,@instance],  :html => { :class => 'form-horizontal' } do |f| %>
    <div class="control-group">
      <%= f.label :title, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :title, :value => @instance.title || "Untitled", :class => 'text_field', :id => "title" %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field', :id => "user_name", :placeholder => 'Webonise' %>
      </div>
    </div>


<div class="imageWrapper clearfix">
<div class="control-group">
    <label class="control-label">Select your flavour</label>
    <div class="controls">
    <ul class="flavorList clearfix">
              <% @flavours.each do |flavor| %>
        <li>
                 <%= f.radio_button :flavor_id , flavor.flavor_id%> <%= flavor.name %> <%= flavor.ram %>
        </li>
              <%end  %>

    </ul>
</div>
</div>
<div class="control-group">
    <label class="control-label">Select your Image</label>
    <div class="controls">
    <ul class="imageList clearfix">

      <% @images.each do |image| %>
        <li>
    <%= f.radio_button :image_id , image.image_id%> <%= image.name %>
        </li>
    <%end  %>
    </ul>
    </div>
</div>
</div>
    <div class="form-actions">
      <%= f.submit "Create Instance", :class => 'customBtn', :id => "submitButton" %>
    </div>
<% end %>

<script type="text/javascript">
    var user_name = new LiveValidation('user_name');
    user_name.add( Validate.Presence );

    var title = new LiveValidation('title');
    title.add( Validate.Presence );
$("#submitButton").click(function(event){
    if($("input:radio:checked").size() < 2)
    {
        alert("Flavour and Image must be need to be selected to create an instance !!!");
        return false;
    }

});


</script>

app/views/instances/edit.html.erb
<%- model_class = Instance -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/instances/index.html.erb
<%- model_class = Instance -%>
<div class="headerWrapper clearfix">

<h1><%= @instances.last.cloud_provider.name.split(" ").first%>'s <%= " "%><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>

<%= link_to "<i class='icon-arrow-left icon-white'></i> BACK".html_safe,
cloud_providers_path, :class => 'customBtn back' %>
<%= link_to "Create Instance",new_cloud_provider_instance_path(@provider), :class => 'btn customBtn pull-right' %>

</div>
<ul class="cloudList">
    <li>
        <ul class="listHeading clearfix">
            <li class="listId"><%= model_class.human_attribute_name(:id) %></li>
            <li class="instanceId"><%= model_class.human_attribute_name(:instance_id) %></li>
            <li class="listState"><%= model_class.human_attribute_name(:state) %></li>
            <li class="listFlavour"><%= model_class.human_attribute_name(:flavor_id) %></li>
            <li class="listName"><%= model_class.human_attribute_name(:name) %></li>
            <li class="listPrivateIP"><%= model_class.human_attribute_name(:private_ip) %></li>
            <li class="listPublicIP"><%= model_class.human_attribute_name(:public_ip) %></li>
            <li class="listDetails"><%= model_class.human_attribute_name(:created_at) %></li>
        </ul>
    </li>
    <% @instances.each do |instance| %>
    <li>
        <%= link_to "<ul class='clearfix'><li class='listId'>#{instance.id}</li><li class='instanceId'>#{instance.instance_id }</li><li class='listState'>#{instance.state}</li><li class='listFlavour'>#{instance.flavor_id}</li><li class='listName'>#{instance.name}</li><li class='listPrivateIP'>#{instance.private_ip}</li><li class='listPublicIP'>#{instance.public_ip}</li><li class='listDetails'>#{l instance.created_at}</li></ul>".html_safe, cloud_provider_instance_path(@provider,instance) %>
               
    </li>
    <% end %>
</ul>

app/views/instances/new.html.erb
<%- model_class = Instance -%>
<div class="newInstancePage">
<div class="headerWrapper clearfix">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>

  <%= link_to "<i class='icon-arrow-left icon-white'></i> BACK".html_safe,
  request.referrer, :class => 'customBtn back' %>

</div>
<%= render :partial => 'form' %>
</div>

app/views/instances/resize_server.html.erb
<div class="page-header">
  <h1>Resize Server</h1>
</div>
<%= form_for [@provider,@instance],  :html => { :class => 'form-horizontal' } do |f| %>
    <div class="control-group">
      <%= f.label :title, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :title, :value => @instance.title || "Untitled", :class => 'text_field', :id => "title" %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field', :id => "user_name" %>
      </div>
    </div>


    <div class="imageWrapper clearfix">
      <div class="control-group">
        <label class="control-label">Select your flavour</label>
        <div class="controls">
          <ul class="flavorList clearfix">
            <% @flavours.each do |flavor| %>
                <li>
                  <%= f.radio_button :flavor_id , flavor.flavor_id%> <%= flavor.name %> <%= flavor.ram %>
                </li>
            <%end  %>

          </ul>
        </div>
      </div>

    </div>
    <div class="form-actions">
      <%= f.submit "Create Instance", :class => 'customBtn', :id => "submitButton" %>
    </div>
<% end %>

<script type="text/javascript">
    var user_name = new LiveValidation('user_name');
    user_name.add( Validate.Presence );

    var title = new LiveValidation('title');
    title.add( Validate.Presence );



</script>

app/views/instances/show.html.erb
<%- model_class = Instance -%>
<div class=" viewInstance">
  <div class="headerWrapper clearfix">
    <h1><%= @instance.cloud_provider.name.split(" ").first%>'s <%= " "%><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
    <%= link_to "<i class='icon-arrow-left icon-white'></i> BACK".html_safe,
                cloud_provider_instances_path, :class => 'customBtn back' %>
  </div>

  <dl class="dl-horizontal">
    <dt><strong>Instance Id:</strong></dt>
    <dd><%= @instance.instance_id %></dd>

    <dt><strong><%= model_class.human_attribute_name(:flavor_id) %>:</strong></dt>
    <% if  @flavor.present? %>
        <dd>Name: <%= @flavor.name %></dd>
        <dd>Ram: <%= @flavor.ram %> <%=  @flavor.ram.to_i < 512 ? "GB" : "MB" if @flavor.ram.present? %></dd>
        <dd>Disk: <%= @flavor.disk%> <%=  @flavor.disk.to_i < 512 ? "GB" : "MB" if @flavor.disk.present? %></dd>
     <% else%>
        <dd><%= @instance.flavor_id %></dd>
     <% end %>
    <dt><strong>Image: </strong></dt>
    <% if  @image.present? %>
    <dd><%= @image.name %></dd>
    <% else %>
        <dd><%= @instance.image_id %></dd>
    <% end %>
    <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
    <dd> <div id="instance_state"><%= @instance.state %></div><%= image_tag("/ajax-loader.gif", :class => "imgLoader") if @instance.state.to_s.downcase == 'building'.strip || @instance.state.to_s.downcase == 'rebooting'.strip %></dd>
    <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
    <dd><%= best_in_place @instance, :name %></dd>
    <dt><strong><%= model_class.human_attribute_name(:private_ip) %>:</strong></dt>
    <dd><div id="private_ip"><%= @instance.private_ip %></div></dd>
    <dt><strong><%= model_class.human_attribute_name(:public_ip) %>:</strong></dt>
    <dd><div id="public_ip"><%= @instance.public_ip %></div></dd>
  </dl>
  <% if @instance.state.to_s.downcase == "building" && @provider.type.to_s.downcase == "rackspace" %>
      <div class="progressWrapper">
        progress :
        <div class="progress progress-striped active">
          <div class="bar" style="width: <%= @instance.progress%>%;"></div>
        </div>
      </div>

  <% end %>
  <div class="form-actions">
    <ul>
      <% if @instance.state != "terminated"%>
      <% if @provider.type.to_s.downcase == "aws"%>
      <%if @instance.state == "stopped"%>
      <li>
        <%= link_to "Start",
                    start_cloud_provider_instance_path(@provider,@instance),
                    :method => 'get',
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-success disableClass' %>
      </li>
      <%end%>
      <%if @instance.state.to_s.downcase == "running"%>
      <li>
        <%= link_to "Stop",stop_cloud_provider_instance_path(@provider,@instance),:method => 'get',:data => { :confirm => t('confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },:class => 'btn btn-danger disableClass' %>
      </li>
      <%end%>
      <% end %>
      <% if @provider.type.to_s.downcase == "rackspace"%>
      <li>
        <%= link_to "Resize",
                    resize_server_cloud_provider_instance_path(@provider,@instance),
                    :method => 'get',
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn customBtn disableClass' %>
      </li>
      <% end %>
      <%if @instance.state != "stopped"%>
      <li>
        <%= link_to "Reboot",
                    reboot_cloud_provider_instance_path(@provider,@instance),
                    :method => 'get',
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-inverse disableClass' %>
      </li>
      <%end%>

      <li>
        <%= link_to "Terminated",
                    cloud_provider_instance_path(@provider,@instance),
                    :method => 'delete',
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-danger disableClass' %>
      </li>
      <% end %>      
    </ul>

  </div>
</div>
<script>
    //Call the yourAjaxCall() function every 1000 millisecond
    setInterval("yourAjaxCall()",1000);
    $(".disableClass").click(function(e){
        if($.trim($("#instance_state").text().toLowerCase()) == "building" || $.trim($("#instance_state").text().toLowerCase()) == 'rebooting')
        {
            alert("Please wait process is already running !!!");
            return false;
        }

    });
    function yourAjaxCall(){

        if($.trim($("#instance_state").text().toLowerCase()) == "building" || $.trim($("#instance_state").text().toLowerCase()) == 'rebooting')
        {
            $.ajax({
                url:"/instances/<%= @instance.id%>/instance_status",
                type: "GET",
                async: false,
                dataType:"json",

                complete:function(resp,type)
                {

                    response = JSON.parse(resp.responseText);
                    $("#instance_state").text(response.state);
                    $("#private_ip").text(response.privateip);
                    $("#public_ip").text(response.publicip);
                    $(".bar").css("width",response.progress +"%");
                    if($.trim($("#instance_state").text().toLowerCase()) != "building" || $.trim($("#instance_state").text().toLowerCase()) != 'rebooting')
                    {
                        $(".progressWrapper").hide();
                        $(".imgLoader").hide();
                    }
                }

            });
        }

    }
</script>