config/routes.rb
Hippo::Application.routes.draw do
  resources :instances  do
    member do
      get :instance_status
    end
  end


  resources :cloud_providers do
    resources :instances do
      member do
        get :resize_server
        get :stop
        get :start
        get :reboot
      end
    end
  end



  get "homes/index"
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions


  resources :html do
    collection do
      get :sign_up
      get :dashboard_none
      get :dashboard
    end
  end
  root :to => 'homes#index'
end

app/models/cloud_provider.rb
# == Schema Information
#
# Table name: cloud_providers
#
#  id         :integer          not null, primary key
#  key        :string(255)
#  name       :string(255)
#  provider   :string(255)
#  secret     :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  type       :string(255)
#  user_id    :integer
#

class CloudProvider < ActiveRecord::Base

  #require 'instance_states.rb'
  #include InstanceStates
  #cattr_accessor :STATES

  attr_accessible :key, :name, :provider, :secret, :type, :user_id
  attr_reader :connect

  after_create :fetch_cloud_data

  has_many :instances, :dependent => :destroy
  belongs_to :user

  def connect!
    @cloud_connection = nil
    puts "I am in Super Class method connect!"
  end

  #To Make The Parent Class Aware of Its Children

  def self.select_options
    puts "#######{descendants.map{ |c| c.to_s.camelcase }.sort}"
    descendants.map{ |c| c.to_s }.sort
  end

  def self.inherited(child)
    child.instance_eval do
      def model_name
        CloudProvider.model_name
      end
    end
    super
  end

end

require_dependency "cloud_providers/aws.rb"
require_dependency "cloud_providers/rackspace.rb"

app/models/cloud_providers/aws.rb
# == Schema Information
#
# Table name: cloud_providers
#
#  id         :integer          not null, primary key
#  key        :string(255)
#  name       :string(255)
#  provider   :string(255)
#  secret     :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  type       :string(255)
#  user_id    :integer
#

class Aws < CloudProvider
  attr_reader :connect

  def connect!
    puts "I am in Base Class method connect! racky"
    @cloud_connection = nil
    @cloud_connection = Fog::Compute.new(
        {
            :provider                 => 'AWS',
            :aws_access_key_id        => self.key,
            :aws_secret_access_key    => self.secret
        })
  end

  def fetch_cloud_data
    connect!
    puts "######connection###{@cloud_connection.inspect}#############"
    instances_list=Instance.get_instances(@cloud_connection,self.id)
    puts "######instances_list###{instances_list.inspect}#############"
    store_instance_list(instances_list,self.id)  unless instances_list.empty?
    self.save
  end

  def store_instance_list instance_list,id
    instance_list.each do |server|
      puts "_________________________"
      puts server.inspect
      puts "_________________________"
      initialize_instance(server,id)
    end
  end

  def initialize_instance data,id
    instance = Instance.new
    instance.public_ip = data.public_ip_address
    instance.private_ip = data.private_ip_address
    instance.flavor_id = data.flavor_id
    instance.name = data.tags['Name']
    instance.state = data.state
    instance.instance_id = data.id
    instance.cloud_provider_id = id
    instance.save
    return instance
  end

  def get_flavors
    flavors = Flavor.where(:flavour_type => "aws")
    unless flavors.present?
      puts "#### i didn't get the flavours of my choices so i creating my own ####"
      Flavor.create_flavor_for_rackspace connect! ,"aws"
      return Flavor.where(:flavour_type => "aws")
    end
    return flavors
  end

  def get_images
    images = Image.where(:flavour_type => "aws")
    return images
  end

  def fetch_instances
    self.instances
  end

end

app/models/cloud_providers/rackspace.rb
# == Schema Information
#
# Table name: cloud_providers
#
#  id         :integer          not null, primary key
#  key        :string(255)
#  name       :string(255)
#  provider   :string(255)
#  secret     :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  type       :string(255)
#  user_id    :integer
#

class Rackspace < CloudProvider

  def connect!
    puts "I am in Base Class method connect! racky"
    @cloud_connection || nil
    puts "I am in Base Class method connect! #{@cloud_connection.inspect}"
    @cloud_connection = Fog::Compute.new(
        {
            :provider                 => 'Rackspace',
            :rackspace_api_key        => self.key,
            :rackspace_username    => self.secret ,
            :rackspace_region => :ord
        })
  end

  def fetch_cloud_data
    connect!
    puts "######connection###{@cloud_connection.inspect}#############"
    instances_list=Instance.get_instances(@cloud_connection,self.id)
    puts "######instances_list###{instances_list.inspect}#############"
    store_instance_list(instances_list,self.id) unless instances_list.empty?
    self.save
  end

  def store_instance_list instance_list,id
    instance_list.each do |server|
      puts "_________________________"
      puts server.inspect
      puts "_________________________"
      initialize_instance(server,id)
    end
  end

  def initialize_instance data,id
    puts "################ID #{id}"
    instance = Instance.new
    instance.public_ip = data.addresses["public"]
    instance.private_ip = data.addresses["private"]
    instance.flavor_id = data.flavor_id
    instance.name = data.name
    instance.instance_id = data.id
    instance.state = data.state
    instance.image_id = data.image_id
    instance.cloud_provider_id = id
    instance.progress = data.progress
    instance.save
    return instance
  end

  def get_flavors
    flavors = Flavor.where(:flavour_type => "Rackspace")
    unless flavors.present?
      puts "#### i didn't get the flavours of my choices so i creating my own ####"
      Flavor.create_flavor_for_rackspace connect! ,"rackspace"
      return Flavor.where(:flavour_type => "Rackspace")
    end
    return flavors
  end

  def get_images
    images = Image.where(:flavour_type => "Rackspace")
    unless images.present?
      puts "#### i didn't get the images of my choices so i creating my own ####"
      Image.create_image_for_rackspace connect! ,"rackspace"
      return Image.where(:flavour_type => "Rackspace")
    end
    return images
  end

  def fetch_instances
    self.instances
  end

end

app/controllers/cloud_providers_controller.rb
class CloudProvidersController < ApplicationController

  # GET /cloud_providers
  # GET /cloud_providers.json
  def index
    @cloud_providers = current_user.cloud_providers

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cloud_providers }
    end
  end

  # GET /cloud_providers/1
  # GET /cloud_providers/1.json
  def show
    @cloud_provider = current_user.cloud_providers.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cloud_provider }
    end
  end

  # GET /cloud_providers/new
  # GET /cloud_providers/new.json
  def new
    @cloud_provider = current_user.cloud_providers.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cloud_provider }
    end
  end

  # GET /cloud_providers/1/edit
  def edit
    @cloud_provider = current_user.cloud_providers.find(params[:id])
  end

  # POST /cloud_providers
  # POST /cloud_providers.json
  def create
    @cloud_provider = params[:cloud_provider][:type].constantize.new(params[:cloud_provider])
    respond_to do |format|
      begin
        @cloud_provider.save
        format.html { redirect_to @cloud_provider, notice: 'Cloud provider was successfully created.' }
        format.json { render json: @cloud_provider, status: :created, location: @cloud_provider }
      rescue
        flash[:error] = "Check the credentials again"
        format.html { render action: "new" }
        format.json { render json: @cloud_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cloud_providers/1
  # PUT /cloud_providers/1.json
  def update
    @cloud_provider = current_user.cloud_providers.find(params[:id])

    respond_to do |format|
      if @cloud_provider.update_attributes(params[:cloud_provider])
        format.html { redirect_to @cloud_provider, notice: 'Cloud provider was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cloud_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cloud_providers/1
  # DELETE /cloud_providers/1.json
  def destroy
    @cloud_provider = current_user.cloud_providers.find(params[:id])
    @cloud_provider.destroy

    respond_to do |format|
      format.html { redirect_to cloud_providers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cloud_providers_helper.rb
module CloudProvidersHelper
end

app/views/cloud_providers/_form.html.erb
<div class="newCloud">

<%= form_for @cloud_provider, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
      <label class="control-label">Access/API key</label>
    <div class="controls">
      <%= f.text_field :key, :class => 'text_field', :id => "key", :placeholder=> 'AKIAKGLSDVSDELKWTF6Q'  %>
    </div>
  </div>
  <div class="control-group">
      <label class="control-label">Cloud Name</label>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field', :id => "user_name", :placeholder=> 'Rackspace Webonise' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Provider, :class => 'control-label' %>
    <div class="controls">
      <%= f.select(:type, options_for_select(CloudProvider.select_options,@cloud_provider.type), {:prompt => "Select Provider", :id => "cloud_provider_type"}) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :secret, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :secret, :class => 'text_field', :id => "secret", :placeholder=> 'Weboniser'  %>
      <%= f.hidden_field :user_id, value: current_user.id %>
        <div class="note"></div>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'customBtn' %>

  </div>
<% end %>
</div>
<script type="text/javascript">
    var user_name = new LiveValidation('user_name');
    user_name.add( Validate.Presence );

    var key = new LiveValidation('key');
    key.add( Validate.Presence );

    var secret = new LiveValidation('secret');
    secret.add( Validate.Presence );

    var cloud_provider_type = new LiveValidation('cloud_provider_type');
    cloud_provider_type.add( Validate.Presence );


</script>

app/views/cloud_providers/_with_cloud_provider.html.erb
<div class="dashboardWrapper">
    <div class="headerWrapper clearfix">
        <h1>Providers</h1>

        <%= link_to t('.new', :default => t("helpers.links.Link your cloud")),
        new_cloud_provider_path,
        :class => 'customBtn' %>


    </div>
<ul>
  <% cloud_providers.each do |cp|%>
    <li>
        <div class="content">
            <div class="<%= cp.type.downcase%>Ribbon"></div>
            <div class="boxHeader">
                <h4><%= cp.name%></h4>
            </div>
            <ul>
                <li>
                    <span>No of instances :</span>
                    <span class="numbers"><%= cp.instances.size%></span>
                </li>
                <li>
                    <span>Active instances :</span>
                    <span class="numbers"><%= cp.type == "Aws" ? cp.instances.where(state: "running").count : cp.instances.where(state: "ACTIVE").count%></span>
                </li>
                 <li>
                    <span>Stop instances :</span>
                    <span class="numbers"><%= cp.type == "Aws" ? cp.instances.where(state: "stopped").count : 0%></span>
                </li>

            </ul>
            <div class="iconsWrapper">
                <%= link_to '',cloud_provider_instances_path(cp), :class => 'viewIcon' %>
                <!-- <a href="" class="editIcon"></a> -->
                <%= link_to '',edit_cloud_provider_path(cp), :class => 'editIcon' %>
                <!-- <a href="" class="deleteIcon"></a> -->
                <%= link_to '',cloud_provider_path(cp),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'deleteIcon' %>
            </div>
            <div class="bottomBox"></div>
        </div>
    </li>
    <% end %>
</ul>
</div>

app/views/cloud_providers/_without_cloud_provider.html.erb
<div class="planeWrapper">
    <div class="planeImg"></div>
    <div class="contentBg">
        <h3>You have no cloud registered</h3>
        <h3>Let&apos;s link one now !! </h3>
        <%= link_to "Register your cloud",new_cloud_provider_path,class: "customBtn" %>

    </div>
</div>

app/views/cloud_providers/edit.html.erb
<%- model_class = CloudProvider -%>

<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cloud_providers/index.html.erb
<% if @cloud_providers.present?%>
<%= render "with_cloud_provider",:cloud_providers => @cloud_providers%>
<%else%>
<%= render "without_cloud_provider"%>
<%end%>

app/views/cloud_providers/new.html.erb
<%- model_class = CloudProvider -%>
<div class="headerWrapper clearfix">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>

      <%= link_to "<i class='icon-arrow-left icon-white'></i> BACK".html_safe,
      cloud_providers_path, :class => 'customBtn back' %>

</div>
<%= render :partial => 'form' %>

app/views/cloud_providers/show.html.erb
<div class="viewProvider">
<%- model_class = CloudProvider -%>
<div class="headerWrapper clearfix">
<h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>

<%= link_to "<i class='icon-arrow-left icon-white'></i> BACK".html_safe,
cloud_providers_path, :class => 'customBtn back' %>

</div>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:key) %>:</strong></dt>
  <dd><%= @cloud_provider.key %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @cloud_provider.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:provider) %>:</strong></dt>
  <dd><%= @cloud_provider.type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:secret) %>:</strong></dt>
  <dd><%= @cloud_provider.secret %></dd>
</dl>

<div class="form-actions form-horizontal">
<div class="control-group">
    <label class="control-label"></label>
    <div class="controls">
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_cloud_provider_path(@cloud_provider), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              cloud_provider_path(@cloud_provider),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
        </div>
</div>
</div>