config/routes.rb
Hippo::Application.routes.draw do
  resources :instances  do
    member do
      get :instance_status
    end
  end


  resources :cloud_providers do
    resources :instances do
      member do
        get :resize_server
        get :stop
        get :start
        get :reboot
      end
    end
  end



  get "homes/index"
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions


  resources :html do
    collection do
      get :sign_up
      get :dashboard_none
      get :dashboard
    end
  end
  root :to => 'homes#index'
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_filter :authorize!
  def index
  	redirect_to  cloud_providers_path if current_user.present?
  end

end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/index.html.erb
<div class="loginScreen">
<div class="contentBg">
    <h3>Sign in as Guest</h3>
    <%= form_tag sessions_path,{:method => :post,:class => "form-horizontal"} do %>
    <div class="control-group">
        <label class="control-label">Enter your name :</label>
        <div class="controls">
            <%= text_field_tag 'user[name]',nil,id:"inputName",placeholder:"John"%>
        </div>
    </div>
        <div class="control-group">
            <label class="control-label">Enter your email :</label>
            <div class="controls">
                <!-- <input type="text" id="inputEmail" placeholder="john@yopmail.com"> -->
                <%= text_field_tag 'user[email]',nil,id:"inputEmail",placeholder:"john@yopmail.com"%>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                    <%= submit_tag 'Login' %>
            </div>
        </div>
    <%end%>
</div>
</div>
<script type="text/javascript">
    var user_name = new LiveValidation('inputName');
    user_name.add( Validate.Presence );

    var key = new LiveValidation('inputEmail');
    key.add( Validate.Presence );
</script>