config/routes.rb
Hippo::Application.routes.draw do
  resources :instances  do
    member do
      get :instance_status
    end
  end


  resources :cloud_providers do
    resources :instances do
      member do
        get :resize_server
        get :stop
        get :start
        get :reboot
      end
    end
  end



  get "homes/index"
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions


  resources :html do
    collection do
      get :sign_up
      get :dashboard_none
      get :dashboard
    end
  end
  root :to => 'homes#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Hippo" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->
  <%= favicon_link_tag "favicon.ico"%>
  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <!-- Size should be 114 x 114 pixels -->

  <%= javascript_include_tag "application" %>
</head>
<body>
<div class="bodyWrapper">

<div class="outer-div">
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/"></a>
      <div class="nav-collapse pull-right">

        <ul class="nav">
          <% if current_user.present?  %>
              <li> <%= link_to "Cloud Providers", cloud_providers_path if current_user.cloud_providers.present?%></li>
              <li> <%= link_to "Log Out", logout_path,:confirm => "Are you sure? Once you logout your all data will be deleted" %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div><!--/.navbar-inner -->
  </div><!-- /nav -->



   </div>
    <div class="container">
      <%= bootstrap_flash%>
        <%= yield %>
    </div> <!-- /container -->

</div><!-- outer-div ends -->
    <footer>
        <p>Our enemy 48 hours, our strength team work, and we did it at <a href="http://www.webonise.com" target="_blank"> Webonise </a> &copy; 2013</p>
        <ul class="clearfix">
            <li>
                <a href="http://www.facebook.com/weboniselab" target="_blank">
                    <span class="links facebook"></span>
                </a>
            </li>
            <li>
                <a href="https://twitter.com/webonise" target="_blank">
                    <span class="links twitter"></span>
                </a>
            </li>
            <li>
                <a href="http://www.linkedin.com/company/391436?goback=%2Efcs_GLHD_webonise+lab_false_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2_*2&amp;trk=ncsrch_hits" target="_blank">
                    <span class="links linkedIn"></span></a>
            </li>
        </ul>
    </footer>
</div><!-- body-wrapper ends -->
<%= javascript_include_tag "banner" %>
</body>
</html>